### ISSUE TITLE
Inactive syntax highlighting

### ISSUE THREAD

**Issue by Juanlu001** [Pybonacci/ipy2wp#5]
Source: https://github.com/Pybonacci/notebooks/blob/master/C%C3%B3mo%20acelerar%20tu%20c%C3%B3digo%20Python%20con%20numba.ipynb

Result: http://pybonacci.org/2015/03/13/como-acelerar-tu-codigo-python-con-numba/

The code fragments appear without syntax highlight.

**Comment by kikocorreoso** [comment]
I think you have used the basic template instead the basicx template. The basicx template provides the nb syntax highlight and removes the prompt numbers.

You can create your own template if you want a specific behavior.

It is not possible to know if someone is using a js syntax highlight lib in their wp box so you should create the template for your use case or choose no highlight (basic) or nb highlight (basicx).

Could the issue be closed?

**Comment by Juanlu001** [comment]
Thanks for the pointer, didn't know basicx was available!

I just used it and properly generated the styles, but it was prepended at the beginning of the article in plaintext... apparently there is no way to enclose that between `<style></style>` tags.

**Comment by Juanlu001** [comment]
May I point out, the WP editor strips out the `<style></style>` tags when you are not the admin. I see what you did here...

**Comment by kikocorreoso** [comment]
WP rules... :-(

Yes, if you want to use something out of the box you should use WP admin. As a user (not admin) you can't do several stuff in WP.

I will update the docs to highlight this.

And I close the issue. If you think this can be improved, pplease, reopen the issue.
