### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by sbushmanov** [Pybonacci/ipy2wp#6]
Is this working as of now?

No joy in using either ipy2wp.js  (no button) or ipy2wp.py (no draft).

Overall, very promising addition to IPython. Any help appreciated.

Regards

**Comment by kikocorreoso** [comment]
Hi.

The javascript extension works for me on linux. It seems there isn't an easy way to make it work globally. I asked in the IPython/Jupyter mail-list with no luck.

OTOH, The `ipy2wp.py` is working for me. Please. let me know what are you doing on the command line and if you have xml-rpc enabled in your wordpress box (http://codex.wordpress.org/XML-RPC_Support).

**Comment by sbushmanov** [comment]
Thanks, really.

I sorted  out the issue with `ipy2wp.py`. It turned out I changed the default address for `xmlrpc.php` on my site some time ago and forgot that. Now, after entering the right address it's working. Cool!

Is there any chance to make `ipy2wp.js` working on my machine? Ubuntu 14.04 here.

No visible response to (no button, no anything):

```
%%javascript
IPython.load_extensions('gist');
```

The extension seems to be installed properly:

```
import IPython
IPython.html.nbextensions.check_nbextension('ipy2wp.js')

True
```

**Comment by kikocorreoso** [comment]
Cool it works the pythonic way.

I think I was incorrect before and I could make it work on windows, not Linux IIRC.

These days I'm busy. Please, If you can remember me this on June and I will take a look on it (I have to travel during some weeks).

Also, if you have some suggestions, please, let me know.

**Comment by sbushmanov** [comment]
The only suggestion so far is to make it working ))))

The idea is great. Being able to post your work to a blog is a must have, better by pressing one button. Lacking this ability prevented me from using Joomla! + K2 (there is no way to post to K2's xmlrps  from an offline editor).

RStudio + knitr have this functionality (== posting from RStudio directly to wordpress). With your help it seems now IPython is going to have this press-one-button functionality too.

So, I'll keep reminding you ))).

**Comment by sbushmanov** [comment]
Well, as far as suggestions concerned.

What about uploading the source notebook and adding to the post a button "Download Notebook", like they have on nbviewer?

Reproducibility is a hot topic in scientific world, and adding such a button will greatly contribute towards ease of running the notebook on local computer and redistribution of the code.

**Comment by kikocorreoso** [comment]
This is an easy stuff to implement. I can see it as a new option pointing to the notebook link but you should know the url previously. Sometimes I create a mardown cell at the end of the notebook with the link so the download will be already included in the notebook. Anyway, this is a good way to collaborate with ipy2wp if you want to create this option yourself ;-)

`ipy2wp [...options...] --download http://github.com/sbushmanov/my-notebooks/Untitled.ipynb`

If you don't know how I can help you.

If you don't have the time I can implement it on June if you remember me this issue!!!

**Comment by sbushmanov** [comment]
Well, thanks for inviting,  I take this as a complement  .... The matter is that .... I'am not a coder ). I come from Finance and my experience with Python (sklearn mainly) is limited to a month or so. I just wanted to add [b]logging to my exercises to keep track of things. Sorry.

**Comment by kikocorreoso** [comment]
Do not worry :-) In some weeks we speak again.

**Comment by sbushmanov** [comment]
I'll be checking my calendar every morning ;)

**Comment by sbushmanov** [comment]
Hi, it's one week into June now and I am taking advantage of my good memory ;)

> I can implement it on June if you remember me this issue!!!

**Comment by kikocorreoso** [comment]
Good memory!!!!

I updated the instructions to install it. Please, read the following:

https://github.com/Pybonacci/ipy2wp#from-the-notebook

And let me know if you find any problem installing it. 

If it is not very clear just let me know.

**Comment by sbushmanov** [comment]
Thanks, it's working for me now.

A couple of additions would make sense:

1. A line or two on how to have this extension loaded on startup:

> Add this line to custom.js  
 IPython.load_extensions('ipy2wp/ipy2wp')

2. If it's not too difficult, downloading *.ipynb notebook to server with a button div at the bottom of the page would be meaningful.

Anyways, thank you very much!

**Comment by kikocorreoso** [comment]
>If it's not too difficult, downloading *.ipynb notebook to server with a button div at the bottom of the page would be meaningful.

What do you mean with this? To upload the nb file to the wp-content folder in your wordpress or add a div in the templates to link to the notebook in a repo or wherever?

**Comment by sbushmanov** [comment]
As of now, I have an opportunity to post the nb to the wp blog. On top of that, I'd like that those interested in rerunning the code on their computers have an opportunity to download the nb (like the button 'Download Notebook' on nbviewer).

To do so,  now I'd have to:

1. manually download the nb to github / wp server
2. manually edit the post to add link or button with a link.

My suggestion was to:
1. download the nb to the wp server along with the posting
2. add a button, e.g. at the bottom of the post 'Download ipynb'

My understanding it will facilitate sharing the code by shortening the path between those who author the code and those who try reproducing it.

**Comment by kikocorreoso** [comment]
I was thinking on that but in the end I discarded to add this as each user has a different behavior. For instance, I have the notebooks on github or bitbucket, others can have their own ftp or their own custom downloads folder on wordpress or whatever. Also, I have to provide a name for the nb (a new field in the form), a path  to the local location of the nb (a new field),...

I think it is easier and it allows for better customisation to paste a link in the wordpress editor and you can have the notebook wherever you want instead in the `wp-contents/uploads` folder only.

**Comment by sbushmanov** [comment]
Thank you anyway, one more time!

Should you some time change your mind and agree that having nb download link next to your post makes sense, I'd be more than glad to discuss what an implementation could. Though, you already seem to have all the necessary ingredients:

-  a field for path, including folder and file name
-  a tickbox 'upload'
-  a div in the html

As far as github and bitbucket are concerned -- that's different. That's for developers. When I code, I git files there for keeping them. When I blog, I want the readers to have an opportunity to download the code without going somewhere else and exploring ways how to download from there. It's the idea behind nbviewer, isn't?

Thanks man!

**Comment by kikocorreoso** [comment]
But for the reader what's the difference between a download link from:

https://raw.githubusercontent.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/master/01_g-h_filter.ipynb

or from

http://yourwordpress.com/wp-content/uploads/2015/06/a_notebook.ipynb

It is pretty easy to add a link in the wordpress editor, a link to wherever the file is, your wordpress box, github or whatever, however, manage this from an UI perspective is not so easy.

I think now this tool solves the hard part for the user in an easy way, the easy part for the user is easily solvable by the user itself 

;-)
