### ISSUE TITLE
Installation instructions for Jupiter 4

### ISSUE THREAD

**Issue by sbushmanov** [Pybonacci/ipy2wp#8]
The extensions stopped loading after upgrading to Ipython/Jupiter 4.

The command:

    %%javascript
    IPython.load_extensions('ipy2wp/ipy2wp')

produces error:

    Javascript error adding output!
    TypeError: IPython.load_extensions is not a function
    See your browser Javascript console for more details.

Is it possible to update install instructions for Jupiter 4?

**Comment by kikocorreoso** [comment]
Are you working on win, Linux, MacOS?

Python version?, complete Jupyter version? Other relevant info that could hellp?

I will try to have a look this evening.

**Comment by sbushmanov** [comment]
Linux Ubuntu 14.04.3 LTS
Python 3.4.3, Anaconda 2.2.0 (64-bit) distribution
jupyter                   1.0.0
jupyter_client         4.1.1
ipython                   4.0.0
ipython-notebook          4.0.4

    print(jupyter_data_dir())
    print(jupyter_path())
    
    /home/sergey/.local/share/jupyter
    ['/home/sergey/.local/share/jupyter', '/home/sergey/anaconda3/share/jupyter', '/usr/local/share/jupyter',   '/usr/share/jupyter']

 

    print(jupyter_config_dir())
    print(jupyter_config_path())
    
    /home/sergey/.jupyter
    ['/home/sergey/.jupyter', '/home/sergey/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter']

I was able to install and load other IPython extensions from [here](https://github.com/ipython-contrib/IPython-notebook-extensions)  and `calico-document-tools` by following instructions from this [answer](http://stackoverflow.com/questions/32046241/how-to-add-automatically-extension-to-jupiter-ipython-notebook), but none of these did help me to load `ipy2wp`.

Best regards!

**Comment by kikocorreoso** [comment]
It seems some stuff has changed and I have to modify some stuff. I will try to study the new changes. In the mean time you can use the python version :-(

**Comment by sbushmanov** [comment]
Thanks man, looking forward for the news from you!

**Comment by kikocorreoso** [comment]
I think it is working now on Jupyter >= 4.0.x.

Let me know if you find any issue.

Updated installation instructions are in the README file.

After the IPython/Jupyter split a bunch of things have changed and I don't have the time to support IPython 3.x and Jupyter 4.x so I decided to maintain only Jupyter 4.x (the version I'm using). If someone needs IPython 3.x support I can accept PRs :-D

If you don't find any issue, please, close it.

Thanks.

**Comment by kikocorreoso** [comment]
BTW, you should clean first your `/home/whatever/.ipython/` dir in order to discard collisions between old and new versions of ipy2wp.

**Comment by sbushmanov** [comment]
Real thanks for the help, it's now working after cleaning out old configs!
